# Generated by Django 5.0.7 on 2024-08-01 17:31

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_category_icon_alter_server_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.channel_banner_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.channel_icon_upload_path
            ),
        ),
    ]
